
       

          <!-- Single button -->
        <div class="btn-group">
          <button           
          type="button" 
          class="btn btn-default dropdown-toggle btn-success" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
            Cadastrar
          </button>
         
        </div>

          <!-- Single button -->
        <div class="btn-group">
          <button 
          type="button" 
          class="btn btn-default dropdown-toggle " 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
           Salve e Fechar
          </button>
         
        </div>

          <!-- Single button -->
        <div class="btn-group">
          <a 
          href=""
          type="button" 
          class="btn btn-default dropdown-toggle btn-danger" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
           Candelar
          </a>
         
        </div>

          <h2 class="sub-header">Novo Cliente</h2>

          <form action="" method="POST">
          <div class="form-group">
            <label for="nameInput">Nome</label>
            <input type="text" class="form-control" name="nome" id="nameInput" placeholder="Name">
          </div>

          <div class="form-group">
            <label for="phoneInput">Telefone</label>
            <input type="text" class="form-control" name="phone" id="phoneInput" placeholder="Telefone">
          </div>

          <div class="form-group">
            <label for="emailInput">Email</label>
            <input type="email" class="form-control" id="emailInput"  name="email" placeholder="Email">
          </div>
         
          <button type="submit" class="btn btn-default">Salvar</button>
        </form>
          
     