
       

          <!-- Single button -->
        <div class="btn-group">
          <button           
          type="button" 
          class="btn btn-default dropdown-toggle btn-success" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
            Salvar
          </button>
         
        </div>

          <!-- Single button -->
        <div class="btn-group">
          <button 
          type="button" 
          class="btn btn-default dropdown-toggle " 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
           Salvar e Fechar
          </button>
         
        </div>

          <!-- Single button -->
        <div class="btn-group">
          <a 
          href=""
          type="button" 
          class="btn btn-default dropdown-toggle btn-danger" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
           Cancelar
          </a>
         
        </div>

          <h2 class="sub-header">Editar Cliente</h2>

          <form action="<?=base_url()?>/editCliente/<?=$this->contact["id_contact"]?>" method="POST">
          <div class="form-group">
            <label for="nameInput">Nome</label>
            <input type="text" class="form-control" name="nome" id="nameInput" placeholder="Nome" value="<?=$this->contact["nome"]?>">
          </div>

          <div class="form-group">
            <label for="phoneInput">Telefone</label>
            <input type="text" class="form-control" name="phone" id="phoneInput" placeholder="Telefone" value="<?=$this->contact["phone"]?>">
          </div>

          <div class="form-group">
            <label for="emailInput">Email</label>
            <input type="email" class="form-control" id="emailInput"  name="email" placeholder="Email" value="<?=$this->contact["email"]?>">
          </div>
         
          <button type="submit" class="btn btn-default">Salvar</button>
        </form>
          
     