
          

          <!-- Single button -->
        <div class="btn-group">
          <a 
          href="<?=base_url()?>/cadastro"
          type="button" 
          class="btn btn-default dropdown-toggle btn-success" 
           
          aria-haspopup="true" 
          aria-expanded="false">
            + Adicionar novo Cliente
          </a>
         
        </div>

          <h2 class="sub-header">Lista de Clientes</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Telefone</th>
                  <th>E-mail</th>
                  <th>Options</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach($this->contacts as $key){ ?>

               
                 
               
                <tr>
                  <td><?=$key["nome"]?></td>
                  <td><?=$key["phone"]?></td>
                  <td><?=$key["email"]?></td>
                   
                  <td>
                    <div class="btn-group" role="group">
                      <a type="button" class="btn btn-default btn-primary" href="<?=base_url()?>/editCliente/<?=$key["id_contact"]?>" >Editar</a>
                       <a type="button" class="btn btn-default btn-danger" href="<?=base_url()?>/deleteCliente/<?=$key["id_contact"]?>">Deletar</a>
                     
                    </div>
                  </td>                  
                </tr>   
                     
                <?php } ?>

              </tbody>
            </table>
          </div>
     