<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="<?=assets('/bootstrap/css/bootstrap.min.css')?>">

	<link rel="stylesheet" type="text/css" href="<?=assets('/style.css')?>">
	<link rel="stylesheet" type="text/css" href="<?=assets('/bootstrap/css/login.css')?>">

	<meta charset="utf-8">
	<title>Login</title>
</head>
<body>

	<div class="container">

      <form class="form-signin" action="<?=base_url()?>/login" method="POST">
        <h3 class="form-signin-heading">Bem Vindo - PHP MVC</h3>
        <label for="inputEmail" class="sr-only">Email</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email" name="login" required autofocus >
        <label for="inputPassword" class="sr-only">Senha</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Senha" name="password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Lembrar-Me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Logar</button>
      </form>

    </div> <!-- /container -->

</body>
</html>